<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.335">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Bogdan G. Popescu">

<title>Lab 8: Statistics</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="lab8_questions_files/libs/clipboard/clipboard.min.js"></script>
<script src="lab8_questions_files/libs/quarto-html/quarto.js"></script>
<script src="lab8_questions_files/libs/quarto-html/popper.min.js"></script>
<script src="lab8_questions_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="lab8_questions_files/libs/quarto-html/anchor.min.js"></script>
<link href="lab8_questions_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="lab8_questions_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="lab8_questions_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="lab8_questions_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="lab8_questions_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<style>html{ scroll-behavior: smooth; }</style>


</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#intro" id="toc-intro" class="nav-link active" data-scroll-target="#intro"><span class="toc-section-number">1</span>  Intro</a></li>
  <li><a href="#loading-the-data" id="toc-loading-the-data" class="nav-link" data-scroll-target="#loading-the-data"><span class="toc-section-number">2</span>  Loading the Data</a></li>
  <li><a href="#cleaning-the-data" id="toc-cleaning-the-data" class="nav-link" data-scroll-target="#cleaning-the-data"><span class="toc-section-number">3</span>  Cleaning the Data</a></li>
  <li><a href="#mapping-the-data" id="toc-mapping-the-data" class="nav-link" data-scroll-target="#mapping-the-data"><span class="toc-section-number">4</span>  Mapping the Data</a></li>
  <li><a href="#performing-a-t-test" id="toc-performing-a-t-test" class="nav-link" data-scroll-target="#performing-a-t-test"><span class="toc-section-number">5</span>  Performing a t-test</a></li>
  <li><a href="#mapping-life-expectancy-in-europe" id="toc-mapping-life-expectancy-in-europe" class="nav-link" data-scroll-target="#mapping-life-expectancy-in-europe"><span class="toc-section-number">6</span>  Mapping Life Expectancy in Europe</a></li>
  <li><a href="#correlation-between-two-variables" id="toc-correlation-between-two-variables" class="nav-link" data-scroll-target="#correlation-between-two-variables"><span class="toc-section-number">7</span>  Correlation between two Variables</a></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Lab 8: Statistics</h1>
<p class="subtitle lead">T-Tests, Choropleth Maps, and Correlations</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Bogdan G. Popescu </p>
          </div>
  </div>
    
  
    
  </div>
  

</header>

<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Removing previous datasets in memory</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">rm</span>(<span class="at">list =</span> <span class="fu">ls</span>())</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="co">#Loading the relevant libraries</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gridExtra)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(purrr)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sf)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rnaturalearth)</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rnaturalearthdata)</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggrepel)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="intro" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Intro</h1>
<p>In this lab, we learn about T-tests and Correlations in pratice. We also learn about mapping.</p>
<p>We learned from the lecture that Z-tests evaluate if there are differences between two groups, when standard deviation or variance is known. The sample size typically should be larger than 30. In most cases however, we will not know the population SD, which is why we will most often use t-tests. To illustrate how t-tests work, let us go back to the sample of Latin American countries and compare them to the world.</p>
</section>
<section id="loading-the-data" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Loading the Data</h1>
<p>Let us go back to the old Life Expectancy dataset. If you don’t have it anymore, you can download Life Expectancy and urbanization from the following links:</p>
<ul>
<li><a href="https://www.dropbox.com/s/k8pwn5x0mechewy/life-expectancy.csv?dl=0" target="_blank">Life expectancy data</a></li>
<li><a href="https://www.dropbox.com/s/wcda5dmqsxr9lzj/share-of-population-urban.csv?dl=0" target="_blank">Urbanization data</a></li>
</ul>
<p>Let us re-examine the distribution of our life expectancy dataset by making a histogram. We need to first load the data:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Setting path</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">setwd</span>(<span class="st">"/Users/bgpopescu/Dropbox/john_cabot/teaching/stats/lab8/"</span>)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="co">#Step1: Loading the data</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>life_expectancy <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="at">file =</span> <span class="st">'./life-expectancy.csv'</span>)</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>urbanization <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="at">file =</span> <span class="st">'./share-of-population-urban.csv'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="cleaning-the-data" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Cleaning the Data</h1>
<p>In the next few line we average life expectancy over country (the original dataset is a panel - with countries and years). This means that we are getting rid of the time component.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Step1: Calculating the mean</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>life_expectancy2<span class="ot">&lt;-</span>life_expectancy<span class="sc">%&gt;%</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Code, Entity)<span class="sc">%&gt;%</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">life_expectancy=</span><span class="fu">mean</span>(Life.expectancy.at.birth..historical.))</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="co">#Step2: Cleaning the Data</span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>weird_labels <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"OWID_KOS"</span>, <span class="st">"OWID_WRL"</span>, <span class="st">""</span>)</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>clean_countries<span class="ot">&lt;-</span><span class="fu">subset</span>(life_expectancy2, <span class="sc">!</span>(Code <span class="sc">%in%</span> weird_labels))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Let us look at our data. We have learned so far to use <code>head</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(clean_countries, <span class="at">n=</span><span class="dv">5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 3
# Groups:   Code [5]
  Code  Entity      life_expectancy
  &lt;chr&gt; &lt;chr&gt;                 &lt;dbl&gt;
1 ABW   Aruba                  70.3
2 AFG   Afghanistan            45.4
3 AGO   Angola                 45.1
4 AIA   Anguilla               69.4
5 ALB   Albania                68.3</code></pre>
</div>
</div>
<p>We can also use potentially a more powerful function to look at our data. This is called <code>glimpse</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(clean_countries)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 235
Columns: 3
Groups: Code [235]
$ Code            &lt;chr&gt; "ABW", "AFG", "AGO", "AIA", "ALB", "AND", "ARE", "ARG"…
$ Entity          &lt;chr&gt; "Aruba", "Afghanistan", "Angola", "Anguilla", "Albania…
$ life_expectancy &lt;dbl&gt; 70.25972, 45.38333, 45.08466, 69.44028, 68.28611, 77.0…</code></pre>
</div>
</div>
<p>As you can see, this tells us exactly how many observations (235), how many columns/variables (3) we have, the first values that these variables take, and the type of variables that we are dealing with: in this case, character and integers. We should consider using <code>glimpse</code> from now on to understand our data better.</p>
</section>
<section id="mapping-the-data" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Mapping the Data</h1>
<p>We will now try to map the data. The package <code>rnaturalearth</code> provides the geographic data for all countries in the world. Use <code>ne_countries</code> to pull country data and choose the scale (<code>rnaturalearthhires</code> is necessary for scale = “large”).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>world <span class="ot">&lt;-</span> <span class="fu">ne_countries</span>(<span class="at">scale =</span> <span class="st">"medium"</span>, <span class="at">returnclass =</span> <span class="st">"sf"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We are now working with a different object. The data that we just cleaned - clean_countries, falls under three different categories of objects: data frame, grouped data frame, a tibble, and a dataframe.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(clean_countries)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "grouped_df" "tbl_df"     "tbl"        "data.frame"</code></pre>
</div>
</div>
<p>Tibble is the central data structure for the set of packages known as the <code>tidyverse</code>, which include <code>dplyr</code>, <code>ggplot2</code>, <code>tidyr</code>, and <code>readr</code>. The general ethos is that tibbles are lazy and surly: they do less and complain more than base data.frames. This forces problems to be tackled earlier and more explicitly, typically leading to code that is more expressive and robust.</p>
<p>If we look at the class for our new object world, it is a different class.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(world)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "sf"         "data.frame"</code></pre>
</div>
</div>
<p>At its most basic, an sf object is a collection of simple features that includes attributes and geometries in the form of a data frame. In other words, it is a data frame (or tibble) with rows of features, columns of attributes, and a special geometry column that contains the spatial aspects of the features.</p>
<p>We can use this format to make maps.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_sf</span>() <span class="sc">+</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_sf</span>(<span class="at">data =</span> world)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="lab8_questions_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>But let us also look more closely at the attribute table of this spatial dataframe.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(world, <span class="at">n =</span> <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 241
Columns: 64
$ scalerank  &lt;int&gt; 3, 1, 1, 1, 1, 3, 3, 1, 1, 1, 3, 1, 5, 3, 1, 1, 1, 1, 1, 1,…
$ featurecla &lt;chr&gt; "Admin-0 country", "Admin-0 country", "Admin-0 country", "A…
$ labelrank  &lt;dbl&gt; 5, 3, 3, 6, 6, 6, 6, 4, 2, 6, 4, 4, 5, 6, 6, 2, 4, 5, 6, 2,…
$ sovereignt &lt;chr&gt; "Netherlands", "Afghanistan", "Angola", "United Kingdom", "…
$ sov_a3     &lt;chr&gt; "NL1", "AFG", "AGO", "GB1", "ALB", "FI1", "AND", "ARE", "AR…
$ adm0_dif   &lt;dbl&gt; 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0,…
$ level      &lt;dbl&gt; 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,…
$ type       &lt;chr&gt; "Country", "Sovereign country", "Sovereign country", "Depen…
$ admin      &lt;chr&gt; "Aruba", "Afghanistan", "Angola", "Anguilla", "Albania", "A…
$ adm0_a3    &lt;chr&gt; "ABW", "AFG", "AGO", "AIA", "ALB", "ALD", "AND", "ARE", "AR…
$ geou_dif   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
$ geounit    &lt;chr&gt; "Aruba", "Afghanistan", "Angola", "Anguilla", "Albania", "A…
$ gu_a3      &lt;chr&gt; "ABW", "AFG", "AGO", "AIA", "ALB", "ALD", "AND", "ARE", "AR…
$ su_dif     &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
$ subunit    &lt;chr&gt; "Aruba", "Afghanistan", "Angola", "Anguilla", "Albania", "A…
$ su_a3      &lt;chr&gt; "ABW", "AFG", "AGO", "AIA", "ALB", "ALD", "AND", "ARE", "AR…
$ brk_diff   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
$ name       &lt;chr&gt; "Aruba", "Afghanistan", "Angola", "Anguilla", "Albania", "A…
$ name_long  &lt;chr&gt; "Aruba", "Afghanistan", "Angola", "Anguilla", "Albania", "A…
$ brk_a3     &lt;chr&gt; "ABW", "AFG", "AGO", "AIA", "ALB", "ALD", "AND", "ARE", "AR…
$ brk_name   &lt;chr&gt; "Aruba", "Afghanistan", "Angola", "Anguilla", "Albania", "A…
$ brk_group  &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…
$ abbrev     &lt;chr&gt; "Aruba", "Afg.", "Ang.", "Ang.", "Alb.", "Aland", "And.", "…
$ postal     &lt;chr&gt; "AW", "AF", "AO", "AI", "AL", "AI", "AND", "AE", "AR", "ARM…
$ formal_en  &lt;chr&gt; "Aruba", "Islamic State of Afghanistan", "People's Republic…
$ formal_fr  &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…
$ note_adm0  &lt;chr&gt; "Neth.", NA, NA, "U.K.", NA, "Fin.", NA, NA, NA, NA, "U.S.A…
$ note_brk   &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, "Multiple claim…
$ name_sort  &lt;chr&gt; "Aruba", "Afghanistan", "Angola", "Anguilla", "Albania", "A…
$ name_alt   &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…
$ mapcolor7  &lt;dbl&gt; 4, 5, 3, 6, 1, 4, 1, 2, 3, 3, 4, 4, 1, 7, 2, 1, 3, 1, 2, 3,…
$ mapcolor8  &lt;dbl&gt; 2, 6, 2, 6, 4, 1, 4, 1, 1, 1, 5, 5, 2, 5, 2, 2, 1, 6, 2, 2,…
$ mapcolor9  &lt;dbl&gt; 2, 8, 6, 6, 1, 4, 1, 3, 3, 2, 1, 1, 2, 9, 5, 2, 3, 5, 5, 1,…
$ mapcolor13 &lt;dbl&gt; 9, 7, 1, 3, 6, 6, 8, 3, 13, 10, 1, NA, 7, 11, 5, 7, 4, 8, 8…
$ pop_est    &lt;dbl&gt; 103065, 28400000, 12799293, 14436, 3639453, 27153, 83888, 4…
$ gdp_md_est &lt;dbl&gt; 2258.0, 22270.0, 110300.0, 108.9, 21810.0, 1563.0, 3660.0, …
$ pop_year   &lt;dbl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…
$ lastcensus &lt;dbl&gt; 2010, 1979, 1970, NA, 2001, NA, 1989, 2010, 2010, 2001, 201…
$ gdp_year   &lt;dbl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…
$ economy    &lt;chr&gt; "6. Developing region", "7. Least developed region", "7. Le…
$ income_grp &lt;chr&gt; "2. High income: nonOECD", "5. Low income", "3. Upper middl…
$ wikipedia  &lt;dbl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…
$ fips_10    &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…
$ iso_a2     &lt;chr&gt; "AW", "AF", "AO", "AI", "AL", "AX", "AD", "AE", "AR", "AM",…
$ iso_a3     &lt;chr&gt; "ABW", "AFG", "AGO", "AIA", "ALB", "ALA", "AND", "ARE", "AR…
$ iso_n3     &lt;chr&gt; "533", "004", "024", "660", "008", "248", "020", "784", "03…
$ un_a3      &lt;chr&gt; "533", "004", "024", "660", "008", "248", "020", "784", "03…
$ wb_a2      &lt;chr&gt; "AW", "AF", "AO", NA, "AL", NA, "AD", "AE", "AR", "AM", "AS…
$ wb_a3      &lt;chr&gt; "ABW", "AFG", "AGO", NA, "ALB", NA, "ADO", "ARE", "ARG", "A…
$ woe_id     &lt;dbl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…
$ adm0_a3_is &lt;chr&gt; "ABW", "AFG", "AGO", "AIA", "ALB", "ALA", "AND", "ARE", "AR…
$ adm0_a3_us &lt;chr&gt; "ABW", "AFG", "AGO", "AIA", "ALB", "ALD", "AND", "ARE", "AR…
$ adm0_a3_un &lt;dbl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…
$ adm0_a3_wb &lt;dbl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…
$ continent  &lt;chr&gt; "North America", "Asia", "Africa", "North America", "Europe…
$ region_un  &lt;chr&gt; "Americas", "Asia", "Africa", "Americas", "Europe", "Europe…
$ subregion  &lt;chr&gt; "Caribbean", "Southern Asia", "Middle Africa", "Caribbean",…
$ region_wb  &lt;chr&gt; "Latin America &amp; Caribbean", "South Asia", "Sub-Saharan Afr…
$ name_len   &lt;dbl&gt; 5, 11, 6, 8, 7, 5, 7, 20, 9, 7, 14, 10, 23, 22, 17, 9, 7, 1…
$ long_len   &lt;dbl&gt; 5, 11, 6, 8, 7, 13, 7, 20, 9, 7, 14, 10, 27, 35, 19, 9, 7, …
$ abbrev_len &lt;dbl&gt; 5, 4, 4, 4, 4, 5, 4, 6, 4, 4, 9, 4, 7, 10, 6, 4, 5, 4, 4, 5…
$ tiny       &lt;dbl&gt; 4, NA, NA, NA, NA, 5, 5, NA, NA, NA, 3, NA, NA, 2, 4, NA, N…
$ homepart   &lt;dbl&gt; NA, 1, 1, NA, 1, NA, 1, 1, 1, 1, NA, 1, NA, NA, 1, 1, 1, 1,…
$ geometry   &lt;MULTIPOLYGON [°]&gt; MULTIPOLYGON (((-69.89912 1..., MULTIPOLYGON (…</code></pre>
</div>
</div>
<p>Our data has a lot of variables, which we don’t need. It seems that the variable adm0_a3 might be good variable to keep: we will use this variable to merge our clean data frame. It might also be helpful to keep admin, continent, sovereignt. These will will help us identify some smaller geographic units (islands) which fall under larger jurisdictions.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>world2<span class="ot">&lt;-</span><span class="fu">subset</span>(world, <span class="at">select =</span> <span class="fu">c</span>(admin, adm0_a3, sovereignt, continent))</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(world2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 241
Columns: 5
$ admin      &lt;chr&gt; "Aruba", "Afghanistan", "Angola", "Anguilla", "Albania", "A…
$ adm0_a3    &lt;chr&gt; "ABW", "AFG", "AGO", "AIA", "ALB", "ALD", "AND", "ARE", "AR…
$ sovereignt &lt;chr&gt; "Netherlands", "Afghanistan", "Angola", "United Kingdom", "…
$ continent  &lt;chr&gt; "North America", "Asia", "Africa", "North America", "Europe…
$ geometry   &lt;MULTIPOLYGON [°]&gt; MULTIPOLYGON (((-69.89912 1..., MULTIPOLYGON (…</code></pre>
</div>
</div>
<p>We now have a spatial dataframe with fewer variables. As mentioned, it seems that a good variable to merge on is <code>adm0_a3</code>. Let us look at both:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>ctries_sp<span class="ot">&lt;-</span>world2<span class="sc">$</span>adm0_a3</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(ctries_sp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> chr [1:241] "ABW" "AFG" "AGO" "AIA" "ALB" "ALD" "AND" "ARE" "ARG" "ARM" ...</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>ctries_df<span class="ot">&lt;-</span>clean_countries<span class="sc">$</span>Code</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(ctries_df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> chr [1:235] "ABW" "AFG" "AGO" "AIA" "ALB" "AND" "ARE" "ARG" "ARM" "ASM" ...</code></pre>
</div>
</div>
<p>Let us now examine whether there are differences when it comes to what is included/excluded in the two lists. We can do this with the help of the <code>setdiff</code> function, which indicates which elements of a vector or data frame X are not existent in a vector or data frame Y.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>countries_dif<span class="ot">&lt;-</span><span class="fu">setdiff</span>(ctries_sp, ctries_df)</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>countries_dif</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "ALD" "ATA" "ATC" "ATF" "BLM" "CYN" "HMD" "IOA" "IOT" "KAS" "KOS" "NFK"
[13] "PCN" "PSX" "SAH" "SDS" "SGS" "SOL"</code></pre>
</div>
</div>
<p>These are countries that are in the spatial dataframe, but not in the our dataframe. What are these countries?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>world3<span class="ot">&lt;-</span><span class="fu">subset</span>(world2, adm0_a3 <span class="sc">%in%</span> countries_dif)</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(world3, <span class="at">n =</span> <span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Simple feature collection with 10 features and 4 fields
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: -180 ymin: -89.99893 xmax: 180 ymax: 60.40581
CRS:           +proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0
                                  admin adm0_a3      sovereignt
5                                 Aland     ALD         Finland
11                           Antarctica     ATA      Antarctica
12          Ashmore and Cartier Islands     ATC       Australia
13  French Southern and Antarctic Lands     ATF          France
27                     Saint Barthelemy     BLM          France
54                      Northern Cyprus     CYN Northern Cyprus
91    Heard Island and McDonald Islands     HMD       Australia
99             Indian Ocean Territories     IOA       Australia
100      British Indian Ocean Territory     IOT  United Kingdom
111                     Siachen Glacier     KAS         Kashmir
                  continent                       geometry
5                    Europe MULTIPOLYGON (((20.61133 60...
11               Antarctica MULTIPOLYGON (((-161.9938 -...
12                  Oceania MULTIPOLYGON (((123.5945 -1...
13  Seven seas (open ocean) MULTIPOLYGON (((69.28242 -4...
27            North America MULTIPOLYGON (((-62.83193 1...
54                     Asia MULTIPOLYGON (((34.00449 35...
91  Seven seas (open ocean) MULTIPOLYGON (((73.70742 -5...
99                     Asia MULTIPOLYGON (((96.91826 -1...
100 Seven seas (open ocean) MULTIPOLYGON (((72.49199 -7...
111                    Asia MULTIPOLYGON (((77.79941 35...</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">list</span>(world3<span class="sc">$</span>admin)[[<span class="dv">1</span>]]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "Aland"                                   
 [2] "Antarctica"                              
 [3] "Ashmore and Cartier Islands"             
 [4] "French Southern and Antarctic Lands"     
 [5] "Saint Barthelemy"                        
 [6] "Northern Cyprus"                         
 [7] "Heard Island and McDonald Islands"       
 [8] "Indian Ocean Territories"                
 [9] "British Indian Ocean Territory"          
[10] "Siachen Glacier"                         
[11] "Kosovo"                                  
[12] "Norfolk Island"                          
[13] "Pitcairn Islands"                        
[14] "Palestine"                               
[15] "Western Sahara"                          
[16] "South Sudan"                             
[17] "South Georgia and South Sandwich Islands"
[18] "Somaliland"                              </code></pre>
</div>
</div>
<p>Let us now perform a left merge so that we can have the data that we cleaned onto the spatial dataframe.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>merged<span class="ot">&lt;-</span><span class="fu">left_join</span>(world2, clean_countries, <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"adm0_a3"</span> <span class="ot">=</span> <span class="st">"Code"</span>))</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(merged, <span class="at">n =</span> <span class="dv">4</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 241
Columns: 7
$ admin           &lt;chr&gt; "Aruba", "Afghanistan", "Angola", "Anguilla", "Albania…
$ adm0_a3         &lt;chr&gt; "ABW", "AFG", "AGO", "AIA", "ALB", "ALD", "AND", "ARE"…
$ sovereignt      &lt;chr&gt; "Netherlands", "Afghanistan", "Angola", "United Kingdo…
$ continent       &lt;chr&gt; "North America", "Asia", "Africa", "North America", "E…
$ Entity          &lt;chr&gt; "Aruba", "Afghanistan", "Angola", "Anguilla", "Albania…
$ life_expectancy &lt;dbl&gt; 70.25972, 45.38333, 45.08466, 69.44028, 68.28611, NA, …
$ geometry        &lt;MULTIPOLYGON [°]&gt; MULTIPOLYGON (((-69.89912 1..., MULTIPOLY…</code></pre>
</div>
</div>
<p>This looks good. Let us now make our first map.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_sf</span>() <span class="sc">+</span></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_sf</span>(<span class="at">data =</span> merged, <span class="fu">aes</span>(<span class="at">fill =</span> life_expectancy))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="lab8_questions_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>We have a just made a choropleth map, which indicates intensity of a variable. Let us now add a few embellishments to make our map nicer.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_sf</span>() <span class="sc">+</span></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_sf</span>(<span class="at">data =</span> merged, <span class="fu">aes</span>(<span class="at">fill =</span> life_expectancy))<span class="sc">+</span></span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme_bw</span>()<span class="sc">+</span></span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">xlab</span>(<span class="st">"X - Longitude"</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">"Y - Latitude"</span>)<span class="sc">+</span></span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">scale_y_continuous</span>(<span class="at">breaks=</span><span class="fu">seq</span>(<span class="sc">-</span><span class="dv">90</span>, <span class="dv">90</span>, <span class="at">by =</span> <span class="dv">10</span>), <span class="at">limits =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">90</span>,<span class="dv">90</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="lab8_questions_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>A map like this has exactly the same structure of regular ggplot graph. The difference is that X is now longitude and Y is latitude.</p>
</section>
<section id="performing-a-t-test" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Performing a t-test</h1>
<p>Let us now go back to our original task, that of calculating a t-test. Because we have this new variable - continent, we no longer need to manually ascribe a continent to our countries. Let us quickly see our labels for the continents.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(merged<span class="sc">$</span>continent)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "North America"           "Asia"                   
[3] "Africa"                  "Europe"                 
[5] "South America"           "Oceania"                
[7] "Antarctica"              "Seven seas (open ocean)"</code></pre>
</div>
</div>
<p>We can use the “South America” label. Note that this does not capture all the countries which we previously referred to as “Latin America.” For example, Mexico is not included here, as it is part of North America. This is to say that Latin America can both referred to as a geographic, but also linguistic space.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>sample_latam<span class="ot">&lt;-</span><span class="fu">subset</span>(merged, continent<span class="sc">==</span><span class="st">"South America"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Let us quickly map South America.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_sf</span>() <span class="sc">+</span></span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_sf</span>(<span class="at">data =</span> sample_latam, <span class="fu">aes</span>(<span class="at">fill =</span> life_expectancy))<span class="sc">+</span></span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme_bw</span>()<span class="sc">+</span></span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">xlab</span>(<span class="st">"X - Longitude"</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">"Y - Latitude"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="lab8_questions_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>We are now ready to perform a t-test to see if the life expectancy in Latin America is different from life expectancy around the world. We should perform one more step: excluding Latin America from our world sample so that we are not comparing the Latin American sample to the world sample (which includes Latin America).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>world_nolatam<span class="ot">&lt;-</span><span class="fu">subset</span>(merged, continent<span class="sc">!=</span><span class="st">"South America"</span>)</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(world_nolatam)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 228
Columns: 7
$ admin           &lt;chr&gt; "Aruba", "Afghanistan", "Angola", "Anguilla", "Albania…
$ adm0_a3         &lt;chr&gt; "ABW", "AFG", "AGO", "AIA", "ALB", "ALD", "AND", "ARE"…
$ sovereignt      &lt;chr&gt; "Netherlands", "Afghanistan", "Angola", "United Kingdo…
$ continent       &lt;chr&gt; "North America", "Asia", "Africa", "North America", "E…
$ Entity          &lt;chr&gt; "Aruba", "Afghanistan", "Angola", "Anguilla", "Albania…
$ life_expectancy &lt;dbl&gt; 70.25972, 45.38333, 45.08466, 69.44028, 68.28611, NA, …
$ geometry        &lt;MULTIPOLYGON [°]&gt; MULTIPOLYGON (((-69.89912 1..., MULTIPOLY…</code></pre>
</div>
</div>
<p>Note that our sample got reduced from 241 (size of world sample including Latin America) to 228 (size of world sample excluding Latin America). Let us now perform a t-test.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(sample_latam<span class="sc">$</span>life_expectancy,</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>        <span class="at">mu=</span><span class="fu">mean</span>(world_nolatam<span class="sc">$</span>life_expectancy, <span class="at">na.rm=</span>T),</span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>        <span class="at">sigma.x=</span><span class="fu">sd</span>(sample_latam<span class="sc">$</span>life_expectancy),</span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>        <span class="at">alternative =</span> <span class="fu">c</span>(<span class="st">"greater"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    One Sample t-test

data:  sample_latam$life_expectancy
t = 0.9924, df = 12, p-value = 0.1703
alternative hypothesis: true mean is greater than 61.75155
95 percent confidence interval:
 60.87175      Inf
sample estimates:
mean of x 
  62.8569 </code></pre>
</div>
</div>
<p>The result indicates that we do not reject the H0 because p is larger than 0.05, so the mean life expectancy for Latin America (as defined here), is not greater than that of the world. But is it less?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(sample_latam<span class="sc">$</span>life_expectancy,</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>        <span class="at">mu=</span><span class="fu">mean</span>(world_nolatam<span class="sc">$</span>life_expectancy, <span class="at">na.rm=</span>T),</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>        <span class="at">sigma.x=</span><span class="fu">sd</span>(sample_latam<span class="sc">$</span>life_expectancy),</span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>        <span class="at">alternative =</span> <span class="fu">c</span>(<span class="st">"less"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    One Sample t-test

data:  sample_latam$life_expectancy
t = 0.9924, df = 12, p-value = 0.8297
alternative hypothesis: true mean is less than 61.75155
95 percent confidence interval:
     -Inf 64.84205
sample estimates:
mean of x 
  62.8569 </code></pre>
</div>
</div>
<p>No, it does not seem to be the case. Is it equal to that of the world?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(sample_latam<span class="sc">$</span>life_expectancy,</span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>        <span class="at">mu=</span><span class="fu">mean</span>(world_nolatam<span class="sc">$</span>life_expectancy, <span class="at">na.rm=</span>T),</span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>        <span class="at">sigma.x=</span><span class="fu">sd</span>(sample_latam<span class="sc">$</span>life_expectancy),</span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>        <span class="at">alternative =</span> <span class="fu">c</span>(<span class="st">"two.sided"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    One Sample t-test

data:  sample_latam$life_expectancy
t = 0.9924, df = 12, p-value = 0.3406
alternative hypothesis: true mean is not equal to 61.75155
95 percent confidence interval:
 60.43009 65.28371
sample estimates:
mean of x 
  62.8569 </code></pre>
</div>
</div>
<p>Yes, statistically it is similar. This test prevents us from rejecting the H0 that the true mean is equal to 61.81599. Thus, the two means are equal.</p>
<p>Another good way to visualize the similarity between the two groups is by using a boxplot.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>merged<span class="sc">$</span>sample<span class="ot">&lt;-</span><span class="cn">NA</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>merged<span class="sc">$</span>sample<span class="ot">&lt;-</span><span class="st">"Rest of the World"</span></span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>merged<span class="sc">$</span>sample[merged<span class="sc">$</span>continent<span class="sc">==</span><span class="st">"South America"</span>]<span class="ot">&lt;-</span><span class="st">"South America"</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(merged, <span class="fu">aes</span>(<span class="at">x =</span> sample, <span class="at">y =</span> life_expectancy, <span class="at">color =</span> sample)) <span class="sc">+</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>() <span class="sc">+</span></span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="lab8_questions_files/figure-html/unnamed-chunk-28-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="mapping-life-expectancy-in-europe" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> Mapping Life Expectancy in Europe</h1>
<p>What if we wanted to examine life expectancy in Europe over time? The first step is to fix the coordinates and add limits to our graph. This time around we need to choose a maximum Y (North Point), minimum Y (South Point), a maximum X (West Point), and minimum X (East Point). One good way would be to take these coordinates from the existing countries. Let us choose four countries that would allow us to decide on the coordinates for Europe: Norway, Portugal, Ukraine, Greece.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>norway<span class="ot">&lt;-</span><span class="fu">subset</span>(merged, Entity <span class="sc">==</span> <span class="st">"Norway"</span>)</span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>nc_geom <span class="ot">&lt;-</span> <span class="fu">st_geometry</span>(norway)</span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>list_points_norway<span class="ot">&lt;-</span>nc_geom[[<span class="dv">1</span>]]</span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a>list_points_norway<span class="ot">&lt;-</span><span class="fu">flatten</span>(list_points_norway)</span>
<span id="cb46-5"><a href="#cb46-5" aria-hidden="true" tabindex="-1"></a>list_points_norway2<span class="ot">&lt;-</span><span class="fu">as.data.frame</span>(<span class="fu">do.call</span>(rbind, list_points_norway))</span>
<span id="cb46-6"><a href="#cb46-6" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(list_points_norway2)<span class="ot">&lt;-</span><span class="fu">c</span>(<span class="st">"lon_x"</span>, <span class="st">"lat_y"</span>)</span>
<span id="cb46-7"><a href="#cb46-7" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(list_points_norway2, <span class="at">n=</span><span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      lon_x    lat_y
1  5.085840 60.30757
2  5.089063 60.18877
3  4.996973 60.19775
4  4.955566 60.24331
5  4.943555 60.27241
6  4.950781 60.34116
7  4.930078 60.41206
8  4.957227 60.44727
9  4.990625 60.45205
10 5.050195 60.38896</code></pre>
</div>
</div>
<p>For our map of Europe we are interested in the Northern most point in Norway. This will be our maximum Y.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>max_lat_y<span class="ot">&lt;-</span><span class="fu">max</span>(list_points_norway2<span class="sc">$</span>lat_y)</span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>max_lat_y</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 80.47783</code></pre>
</div>
</div>
<p>Let us now get another country that is in the south: Greece.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>greece<span class="ot">&lt;-</span><span class="fu">subset</span>(merged, Entity <span class="sc">==</span> <span class="st">"Greece"</span>)</span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>nc_geom <span class="ot">&lt;-</span> <span class="fu">st_geometry</span>(greece)</span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a>list_points_greece<span class="ot">&lt;-</span>nc_geom[[<span class="dv">1</span>]]</span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a>list_points_greece<span class="ot">&lt;-</span><span class="fu">flatten</span>(list_points_greece)</span>
<span id="cb50-5"><a href="#cb50-5" aria-hidden="true" tabindex="-1"></a>list_points_greece2<span class="ot">&lt;-</span><span class="fu">as.data.frame</span>(<span class="fu">do.call</span>(rbind, list_points_greece))</span>
<span id="cb50-6"><a href="#cb50-6" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(list_points_greece2)<span class="ot">&lt;-</span><span class="fu">c</span>(<span class="st">"lon_x"</span>, <span class="st">"lat_y"</span>)</span>
<span id="cb50-7"><a href="#cb50-7" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(list_points_greece2, <span class="at">n=</span><span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      lon_x    lat_y
1  23.85225 35.53545
2  23.92061 35.52817
3  24.01328 35.52944
4  24.03438 35.53540
5  24.09336 35.59385
6  24.16602 35.59521
7  24.19775 35.53745
8  24.12402 35.51084
9  24.10898 35.49580
10 24.12314 35.48364</code></pre>
</div>
</div>
<p>For our map of Europe we are interested in the Southern most point in Greece This will be the minimum Y.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>min_lat_y<span class="ot">&lt;-</span><span class="fu">min</span>(list_points_greece2<span class="sc">$</span>lat_y)</span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>min_lat_y</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 34.93447</code></pre>
</div>
</div>
<p>Let us now get a country in the East: Ukraine.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>ukraine<span class="ot">&lt;-</span><span class="fu">subset</span>(merged, Entity <span class="sc">==</span> <span class="st">"Ukraine"</span>)</span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a>nc_geom <span class="ot">&lt;-</span> <span class="fu">st_geometry</span>(ukraine)</span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a>list_points_ukraine<span class="ot">&lt;-</span>nc_geom[[<span class="dv">1</span>]]</span>
<span id="cb54-4"><a href="#cb54-4" aria-hidden="true" tabindex="-1"></a>list_points_ukraine<span class="ot">&lt;-</span><span class="fu">flatten</span>(list_points_ukraine)</span>
<span id="cb54-5"><a href="#cb54-5" aria-hidden="true" tabindex="-1"></a>list_points_ukraine2<span class="ot">&lt;-</span><span class="fu">as.data.frame</span>(<span class="fu">do.call</span>(rbind, list_points_ukraine))</span>
<span id="cb54-6"><a href="#cb54-6" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(list_points_ukraine2)<span class="ot">&lt;-</span><span class="fu">c</span>(<span class="st">"lon_x"</span>, <span class="st">"lat_y"</span>)</span>
<span id="cb54-7"><a href="#cb54-7" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(list_points_ukraine2, <span class="at">n=</span><span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      lon_x    lat_y
1  32.01221 46.20391
2  32.15010 46.15469
3  32.00938 46.16782
4  31.70020 46.21406
5  31.56387 46.25776
6  31.52871 46.30659
7  31.50879 46.37314
8  31.58486 46.30317
9  31.63848 46.27256
10 32.01221 46.20391</code></pre>
</div>
</div>
<p>For our map of Europe we are interested in the Eastern most point in Ukraine This will be the maximum X.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a>max_lon_x<span class="ot">&lt;-</span><span class="fu">max</span>(list_points_ukraine2<span class="sc">$</span>lon_x)</span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a>max_lon_x</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 40.12832</code></pre>
</div>
</div>
<p>Let’s choose now a country in the West: Portugal</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a>portugal<span class="ot">&lt;-</span><span class="fu">subset</span>(merged, Entity <span class="sc">==</span> <span class="st">"Portugal"</span>)</span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a>nc_geom <span class="ot">&lt;-</span> <span class="fu">st_geometry</span>(portugal)</span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a>list_points_portugal<span class="ot">&lt;-</span>nc_geom[[<span class="dv">1</span>]]</span>
<span id="cb58-4"><a href="#cb58-4" aria-hidden="true" tabindex="-1"></a>list_points_portugal<span class="ot">&lt;-</span><span class="fu">flatten</span>(list_points_portugal)</span>
<span id="cb58-5"><a href="#cb58-5" aria-hidden="true" tabindex="-1"></a>list_points_portugal2<span class="ot">&lt;-</span><span class="fu">as.data.frame</span>(<span class="fu">do.call</span>(rbind, list_points_portugal))</span>
<span id="cb58-6"><a href="#cb58-6" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(list_points_portugal2)<span class="ot">&lt;-</span><span class="fu">c</span>(<span class="st">"lon_x"</span>, <span class="st">"lat_y"</span>)</span>
<span id="cb58-7"><a href="#cb58-7" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(list_points_portugal2, <span class="at">n=</span><span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       lon_x    lat_y
1  -17.19087 32.86860
2  -17.05449 32.81587
3  -16.92920 32.84141
4  -16.77397 32.77354
5  -16.69326 32.75801
6  -16.76528 32.70972
7  -16.83740 32.64829
8  -17.01826 32.66279
9  -17.17119 32.72188
10 -17.22603 32.76685</code></pre>
</div>
</div>
<p>For our map of Europe we are interested in the Western most point in Portugal. This will be the minimum X.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a>min_lon_x<span class="ot">&lt;-</span><span class="fu">min</span>(list_points_portugal2<span class="sc">$</span>lon_x)</span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a>min_lon_x</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -31.28296</code></pre>
</div>
</div>
<p>We are now ready:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a>figure1<span class="ot">&lt;-</span><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_sf</span>() <span class="sc">+</span></span>
<span id="cb62-3"><a href="#cb62-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_sf</span>(<span class="at">data =</span> merged, <span class="fu">aes</span>(<span class="at">fill =</span> life_expectancy))<span class="sc">+</span></span>
<span id="cb62-4"><a href="#cb62-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme_bw</span>()<span class="sc">+</span></span>
<span id="cb62-5"><a href="#cb62-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">xlab</span>(<span class="st">"X - Longitude"</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">"Y - Latitude"</span>)<span class="sc">+</span></span>
<span id="cb62-6"><a href="#cb62-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">coord_sf</span>(<span class="at">xlim =</span> <span class="fu">c</span>(min_lon_x, max_lon_x), <span class="at">ylim =</span> <span class="fu">c</span>(min_lat_y, max_lat_y), <span class="at">expand =</span> <span class="cn">FALSE</span>)</span>
<span id="cb62-7"><a href="#cb62-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-8"><a href="#cb62-8" aria-hidden="true" tabindex="-1"></a><span class="fu">ggsave</span>(figure1, <span class="at">file =</span> <span class="st">"./figure1.jpg"</span>, </span>
<span id="cb62-9"><a href="#cb62-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">height =</span> <span class="dv">20</span>, <span class="at">width =</span> <span class="dv">20</span>, </span>
<span id="cb62-10"><a href="#cb62-10" aria-hidden="true" tabindex="-1"></a>       <span class="at">units =</span> <span class="st">"cm"</span>, <span class="at">dpi =</span> <span class="dv">300</span>)</span>
<span id="cb62-11"><a href="#cb62-11" aria-hidden="true" tabindex="-1"></a>figure1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="lab8_questions_files/figure-html/unnamed-chunk-37-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Let us also visualize the points that we calculated. But to make things easier, we should create a df.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a>euro_extreme<span class="ot">&lt;-</span><span class="fu">data.frame</span>(<span class="at">x_lon=</span><span class="fu">c</span>(min_lon_x, max_lon_x, min_lon_x, max_lon_x),</span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a>                         <span class="at">y_lat=</span><span class="fu">c</span>(min_lat_y, max_lat_y, max_lat_y, min_lat_y),</span>
<span id="cb63-3"><a href="#cb63-3" aria-hidden="true" tabindex="-1"></a>                         <span class="at">name =</span> (<span class="fu">c</span>(<span class="st">"South-West"</span>, <span class="st">"North-East"</span>, <span class="st">"North-West"</span>, <span class="st">"South-East"</span>)))</span>
<span id="cb63-4"><a href="#cb63-4" aria-hidden="true" tabindex="-1"></a>euro_extreme</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      x_lon    y_lat       name
1 -31.28296 34.93447 South-West
2  40.12832 80.47783 North-East
3 -31.28296 80.47783 North-West
4  40.12832 34.93447 South-East</code></pre>
</div>
</div>
<p>Let us visualize the four points that we calculated.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a>figure1<span class="ot">&lt;-</span><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_sf</span>() <span class="sc">+</span></span>
<span id="cb65-3"><a href="#cb65-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_sf</span>(<span class="at">data =</span> merged, <span class="fu">aes</span>(<span class="at">fill =</span> life_expectancy))<span class="sc">+</span></span>
<span id="cb65-4"><a href="#cb65-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_point</span>(<span class="at">data=</span> euro_extreme, <span class="fu">aes</span>(<span class="at">x=</span>x_lon, </span>
<span id="cb65-5"><a href="#cb65-5" aria-hidden="true" tabindex="-1"></a>                 <span class="at">y=</span>y_lat), </span>
<span id="cb65-6"><a href="#cb65-6" aria-hidden="true" tabindex="-1"></a>             <span class="at">fill=</span><span class="st">"blue"</span>, <span class="at">color=</span><span class="st">"darkred"</span>, <span class="at">size=</span><span class="dv">3</span>)<span class="sc">+</span></span>
<span id="cb65-7"><a href="#cb65-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_label_repel</span>(<span class="at">data=</span> euro_extreme, <span class="fu">aes</span>(<span class="at">x=</span>x_lon, <span class="at">y=</span>y_lat,</span>
<span id="cb65-8"><a href="#cb65-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">label =</span> name), <span class="at">fill =</span> <span class="fu">alpha</span>(<span class="fu">c</span>(<span class="st">"white"</span>),<span class="fl">0.8</span>))<span class="sc">+</span></span>
<span id="cb65-9"><a href="#cb65-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme_bw</span>()<span class="sc">+</span></span>
<span id="cb65-10"><a href="#cb65-10" aria-hidden="true" tabindex="-1"></a>    <span class="fu">xlab</span>(<span class="st">"X - Longitude"</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">"Y - Latitude"</span>)<span class="sc">+</span></span>
<span id="cb65-11"><a href="#cb65-11" aria-hidden="true" tabindex="-1"></a>    <span class="fu">coord_sf</span>(<span class="at">xlim =</span> <span class="fu">c</span>(min_lon_x<span class="dv">-3</span>, max_lon_x<span class="sc">+</span><span class="dv">3</span>), <span class="at">ylim =</span> <span class="fu">c</span>(min_lat_y<span class="dv">-3</span>, max_lat_y<span class="sc">+</span><span class="dv">3</span>), <span class="at">expand =</span> <span class="cn">FALSE</span>)</span>
<span id="cb65-12"><a href="#cb65-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb65-13"><a href="#cb65-13" aria-hidden="true" tabindex="-1"></a>figure1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="lab8_questions_files/figure-html/unnamed-chunk-39-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>This looks pretty good. Next step is to redo the merge in our data. Remember that we calculated average life expectancy for the entire period: historical years up to the present day. Thus, we need to do a new merge in which we merge the spatial dataframe to the specific year on life expectancy.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="co">#life_expectancy$Code</span></span>
<span id="cb66-2"><a href="#cb66-2" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(life_expectancy)[<span class="dv">4</span>]<span class="ot">&lt;-</span><span class="st">"life_expectancy_values"</span></span>
<span id="cb66-3"><a href="#cb66-3" aria-hidden="true" tabindex="-1"></a>life_expectancy_1950<span class="ot">&lt;-</span><span class="fu">subset</span>(life_expectancy, Year<span class="sc">==</span><span class="dv">1950</span>)</span>
<span id="cb66-4"><a href="#cb66-4" aria-hidden="true" tabindex="-1"></a>world_1950<span class="ot">&lt;-</span><span class="fu">left_join</span>(world2, life_expectancy_1950, <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"adm0_a3"</span><span class="ot">=</span><span class="st">"Code"</span>))</span>
<span id="cb66-5"><a href="#cb66-5" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(world_1950)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 241
Columns: 8
$ admin                  &lt;chr&gt; "Aruba", "Afghanistan", "Angola", "Anguilla", "…
$ adm0_a3                &lt;chr&gt; "ABW", "AFG", "AGO", "AIA", "ALB", "ALD", "AND"…
$ sovereignt             &lt;chr&gt; "Netherlands", "Afghanistan", "Angola", "United…
$ continent              &lt;chr&gt; "North America", "Asia", "Africa", "North Ameri…
$ Entity                 &lt;chr&gt; "Aruba", "Afghanistan", "Angola", "Anguilla", "…
$ Year                   &lt;int&gt; 1950, 1950, 1950, 1950, 1950, NA, 1950, 1950, 1…
$ life_expectancy_values &lt;dbl&gt; 57.2, 27.7, 36.3, 55.3, 44.7, NA, 64.6, 41.1, 6…
$ geometry               &lt;MULTIPOLYGON [°]&gt; MULTIPOLYGON (((-69.89912 1..., MU…</code></pre>
</div>
</div>
<p>What is we were interested in life expectancy in Europe in 1950.</p>
<p>Let us map life expectancy in 1950.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a>figure2<span class="ot">&lt;-</span><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb68-2"><a href="#cb68-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_sf</span>(<span class="at">data =</span> world_1950, <span class="fu">aes</span>(<span class="at">fill =</span> life_expectancy_values))<span class="sc">+</span></span>
<span id="cb68-3"><a href="#cb68-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme_bw</span>()<span class="sc">+</span></span>
<span id="cb68-4"><a href="#cb68-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">xlab</span>(<span class="st">"X - Longitude"</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">"Y - Latitude"</span>)<span class="sc">+</span></span>
<span id="cb68-5"><a href="#cb68-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">coord_sf</span>(<span class="at">xlim =</span> <span class="fu">c</span>(min_lon_x, max_lon_x), <span class="at">ylim =</span> <span class="fu">c</span>(min_lat_y, max_lat_y), <span class="at">expand =</span> <span class="cn">FALSE</span>)</span>
<span id="cb68-6"><a href="#cb68-6" aria-hidden="true" tabindex="-1"></a>figure2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="lab8_questions_files/figure-html/unnamed-chunk-41-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Let us map life expectancy in 2020.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a>life_expectancy_2020<span class="ot">&lt;-</span><span class="fu">subset</span>(life_expectancy, Year<span class="sc">==</span><span class="dv">2020</span>)</span>
<span id="cb69-2"><a href="#cb69-2" aria-hidden="true" tabindex="-1"></a>world_2020<span class="ot">&lt;-</span><span class="fu">left_join</span>(world2, life_expectancy_2020, <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"adm0_a3"</span><span class="ot">=</span><span class="st">"Code"</span>))</span>
<span id="cb69-3"><a href="#cb69-3" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(world_2020)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 241
Columns: 8
$ admin                  &lt;chr&gt; "Aruba", "Afghanistan", "Angola", "Anguilla", "…
$ adm0_a3                &lt;chr&gt; "ABW", "AFG", "AGO", "AIA", "ALB", "ALD", "AND"…
$ sovereignt             &lt;chr&gt; "Netherlands", "Afghanistan", "Angola", "United…
$ continent              &lt;chr&gt; "North America", "Asia", "Africa", "North Ameri…
$ Entity                 &lt;chr&gt; "Aruba", "Afghanistan", "Angola", "Anguilla", "…
$ Year                   &lt;int&gt; 2020, 2020, 2020, 2020, 2020, NA, 2020, 2020, 2…
$ life_expectancy_values &lt;dbl&gt; 75.7, 62.6, 62.3, 76.9, 77.0, NA, 79.0, 78.9, 7…
$ geometry               &lt;MULTIPOLYGON [°]&gt; MULTIPOLYGON (((-69.89912 1..., MU…</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a>figure3<span class="ot">&lt;-</span><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_sf</span>() <span class="sc">+</span></span>
<span id="cb71-3"><a href="#cb71-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_sf</span>(<span class="at">data =</span> world_2020, <span class="fu">aes</span>(<span class="at">fill =</span> life_expectancy_values))<span class="sc">+</span></span>
<span id="cb71-4"><a href="#cb71-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme_bw</span>()<span class="sc">+</span></span>
<span id="cb71-5"><a href="#cb71-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">xlab</span>(<span class="st">"X - Longitude"</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">"Y - Latitude"</span>)<span class="sc">+</span></span>
<span id="cb71-6"><a href="#cb71-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">coord_sf</span>(<span class="at">xlim =</span> <span class="fu">c</span>(min_lon_x, max_lon_x), <span class="at">ylim =</span> <span class="fu">c</span>(min_lat_y, max_lat_y), <span class="at">expand =</span> <span class="cn">FALSE</span>)</span>
<span id="cb71-7"><a href="#cb71-7" aria-hidden="true" tabindex="-1"></a>figure3</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="lab8_questions_files/figure-html/unnamed-chunk-43-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Let us put them side by side.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a><span class="fu">grid.arrange</span>(figure2, figure3, <span class="at">ncol=</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="lab8_questions_files/figure-html/unnamed-chunk-44-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>We don’t see much of a difference because we also need to fix the color scheme in a way that has the same minmum and maximum. This is how we do this:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a>vmax <span class="ot">&lt;-</span> <span class="fu">max</span>(life_expectancy<span class="sc">$</span>life_expectancy_values, <span class="at">na.rm=</span>T)</span>
<span id="cb73-2"><a href="#cb73-2" aria-hidden="true" tabindex="-1"></a>vmin <span class="ot">&lt;-</span> <span class="fu">min</span>(life_expectancy<span class="sc">$</span>life_expectancy_values, <span class="at">na.rm=</span>T)</span>
<span id="cb73-3"><a href="#cb73-3" aria-hidden="true" tabindex="-1"></a>vmax</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 86.5</code></pre>
</div>
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a>vmin</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 12</code></pre>
</div>
</div>
<p>Let us now replot the maps</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggpubr)</span>
<span id="cb77-2"><a href="#cb77-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-3"><a href="#cb77-3" aria-hidden="true" tabindex="-1"></a>figure2<span class="ot">&lt;-</span><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb77-4"><a href="#cb77-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_sf</span>() <span class="sc">+</span></span>
<span id="cb77-5"><a href="#cb77-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_sf</span>(<span class="at">data =</span> world_1950, <span class="fu">aes</span>(<span class="at">fill =</span> life_expectancy_values))<span class="sc">+</span></span>
<span id="cb77-6"><a href="#cb77-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme_bw</span>()<span class="sc">+</span></span>
<span id="cb77-7"><a href="#cb77-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">xlab</span>(<span class="st">"X - Longitude"</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">"Y - Latitude"</span>)<span class="sc">+</span></span>
<span id="cb77-8"><a href="#cb77-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">coord_sf</span>(<span class="at">xlim =</span> <span class="fu">c</span>(min_lon_x, max_lon_x), <span class="at">ylim =</span> <span class="fu">c</span>(min_lat_y, max_lat_y), <span class="at">expand =</span> <span class="cn">FALSE</span>)<span class="sc">+</span></span>
<span id="cb77-9"><a href="#cb77-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_gradient</span>(<span class="at">limits=</span><span class="fu">c</span>(vmin, vmax))</span>
<span id="cb77-10"><a href="#cb77-10" aria-hidden="true" tabindex="-1"></a>  <span class="co">#theme(legend.position="none")</span></span>
<span id="cb77-11"><a href="#cb77-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-12"><a href="#cb77-12" aria-hidden="true" tabindex="-1"></a>figure3<span class="ot">&lt;-</span><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb77-13"><a href="#cb77-13" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_sf</span>() <span class="sc">+</span></span>
<span id="cb77-14"><a href="#cb77-14" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_sf</span>(<span class="at">data =</span> world_2020, <span class="fu">aes</span>(<span class="at">fill =</span> life_expectancy_values))<span class="sc">+</span></span>
<span id="cb77-15"><a href="#cb77-15" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme_bw</span>()<span class="sc">+</span></span>
<span id="cb77-16"><a href="#cb77-16" aria-hidden="true" tabindex="-1"></a>    <span class="fu">xlab</span>(<span class="st">"X - Longitude"</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">"Y - Latitude"</span>)<span class="sc">+</span></span>
<span id="cb77-17"><a href="#cb77-17" aria-hidden="true" tabindex="-1"></a>    <span class="fu">coord_sf</span>(<span class="at">xlim =</span> <span class="fu">c</span>(min_lon_x, max_lon_x), <span class="at">ylim =</span> <span class="fu">c</span>(min_lat_y, max_lat_y), <span class="at">expand =</span> <span class="cn">FALSE</span>)<span class="sc">+</span></span>
<span id="cb77-18"><a href="#cb77-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_gradient</span>(<span class="at">limits=</span><span class="fu">c</span>(vmin, vmax))</span>
<span id="cb77-19"><a href="#cb77-19" aria-hidden="true" tabindex="-1"></a>  <span class="co">#theme(legend.position="none")</span></span>
<span id="cb77-20"><a href="#cb77-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-21"><a href="#cb77-21" aria-hidden="true" tabindex="-1"></a><span class="fu">ggarrange</span>(figure2, figure3, <span class="at">ncol=</span><span class="dv">2</span>, <span class="at">common.legend =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="lab8_questions_files/figure-html/unnamed-chunk-46-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Now, the differences are more visible. What if were interested in plotting the change in life expectancy between 1950 and 2020?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a>life_expectancy_1950_2020<span class="ot">&lt;-</span><span class="fu">subset</span>(life_expectancy, Year <span class="sc">%in%</span> <span class="fu">c</span>(<span class="dv">1950</span>, <span class="dv">2020</span>))</span>
<span id="cb78-2"><a href="#cb78-2" aria-hidden="true" tabindex="-1"></a>life_expectancy_1950_2020b<span class="ot">&lt;-</span>life_expectancy_1950_2020<span class="sc">%&gt;%</span></span>
<span id="cb78-3"><a href="#cb78-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Code) <span class="sc">%&gt;%</span></span>
<span id="cb78-4"><a href="#cb78-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">differ=</span>life_expectancy_values <span class="sc">-</span> <span class="fu">lag</span>(life_expectancy_values))</span>
<span id="cb78-5"><a href="#cb78-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-6"><a href="#cb78-6" aria-hidden="true" tabindex="-1"></a>life_expectancy_1950_2020c<span class="ot">&lt;-</span><span class="fu">subset</span>(life_expectancy_1950_2020b, Code<span class="sc">!=</span><span class="st">""</span> <span class="sc">&amp;</span> <span class="sc">!</span><span class="fu">is.na</span>(differ))</span>
<span id="cb78-7"><a href="#cb78-7" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(life_expectancy_1950_2020c)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 237
Columns: 2
Groups: Code [237]
$ Code   &lt;chr&gt; "ABW", "AFG", "AGO", "AIA", "ALB", "AND", "ARE", "ARG", "ARM", …
$ differ &lt;dbl&gt; 18.5, 34.9, 26.0, 21.6, 32.3, 14.4, 37.8, 14.7, 12.9, 11.4, 21.…</code></pre>
</div>
</div>
<p>Let us now plot the change.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a>world_change<span class="ot">&lt;-</span><span class="fu">left_join</span>(world2, life_expectancy_1950_2020c, <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"adm0_a3"</span><span class="ot">=</span><span class="st">"Code"</span>))</span>
<span id="cb80-2"><a href="#cb80-2" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(world_change)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 241
Columns: 6
$ admin      &lt;chr&gt; "Aruba", "Afghanistan", "Angola", "Anguilla", "Albania", "A…
$ adm0_a3    &lt;chr&gt; "ABW", "AFG", "AGO", "AIA", "ALB", "ALD", "AND", "ARE", "AR…
$ sovereignt &lt;chr&gt; "Netherlands", "Afghanistan", "Angola", "United Kingdom", "…
$ continent  &lt;chr&gt; "North America", "Asia", "Africa", "North America", "Europe…
$ differ     &lt;dbl&gt; 18.5, 34.9, 26.0, 21.6, 32.3, NA, 14.4, 37.8, 14.7, 12.9, 1…
$ geometry   &lt;MULTIPOLYGON [°]&gt; MULTIPOLYGON (((-69.89912 1..., MULTIPOLYGON (…</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb82"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a>figure4<span class="ot">&lt;-</span><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb82-2"><a href="#cb82-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_sf</span>() <span class="sc">+</span></span>
<span id="cb82-3"><a href="#cb82-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_sf</span>(<span class="at">data =</span> world_change, <span class="fu">aes</span>(<span class="at">fill =</span> differ))<span class="sc">+</span></span>
<span id="cb82-4"><a href="#cb82-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme_bw</span>()<span class="sc">+</span></span>
<span id="cb82-5"><a href="#cb82-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">xlab</span>(<span class="st">"X - Longitude"</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">"Y - Latitude"</span>)<span class="sc">+</span></span>
<span id="cb82-6"><a href="#cb82-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">coord_sf</span>(<span class="at">xlim =</span> <span class="fu">c</span>(min_lon_x, max_lon_x), <span class="at">ylim =</span> <span class="fu">c</span>(min_lat_y, max_lat_y), <span class="at">expand =</span> <span class="cn">FALSE</span>)<span class="sc">+</span></span>
<span id="cb82-7"><a href="#cb82-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_gradient</span>(<span class="at">limits=</span><span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">35</span>))</span>
<span id="cb82-8"><a href="#cb82-8" aria-hidden="true" tabindex="-1"></a>figure4</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="lab8_questions_files/figure-html/unnamed-chunk-49-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>What is the country in Europe with the highest change in life expectancy between 1950 and 2020?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb83"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a>world_change_res<span class="ot">&lt;-</span><span class="fu">subset</span>(world_change, continent<span class="sc">==</span><span class="st">"Europe"</span>)</span>
<span id="cb83-2"><a href="#cb83-2" aria-hidden="true" tabindex="-1"></a>world_change_resx<span class="ot">&lt;-</span><span class="fu">subset</span>(world_change_res, differ<span class="sc">==</span><span class="fu">max</span>(world_change_res<span class="sc">$</span>differ, <span class="at">na.rm=</span>T))</span>
<span id="cb83-3"><a href="#cb83-3" aria-hidden="true" tabindex="-1"></a>world_change_resx<span class="sc">$</span>admin</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Albania"</code></pre>
</div>
</div>
<p>What is the country in Europe with the lowest change in life expectancy between 1950 and 2020?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb85"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb85-1"><a href="#cb85-1" aria-hidden="true" tabindex="-1"></a>world_change_resx<span class="ot">&lt;-</span><span class="fu">subset</span>(world_change_res, differ<span class="sc">==</span><span class="fu">min</span>(world_change_res<span class="sc">$</span>differ, <span class="at">na.rm=</span>T))</span>
<span id="cb85-2"><a href="#cb85-2" aria-hidden="true" tabindex="-1"></a>world_change_resx<span class="sc">$</span>admin</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Latvia"</code></pre>
</div>
</div>
</section>
<section id="correlation-between-two-variables" class="level1" data-number="7">
<h1 data-number="7"><span class="header-section-number">7</span> Correlation between two Variables</h1>
<p>Let us now calculate the correlation between urbanization and life expectancy.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb87"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(urbanization)[<span class="dv">4</span>]<span class="ot">&lt;-</span><span class="st">"urbanization"</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb88"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb88-1"><a href="#cb88-1" aria-hidden="true" tabindex="-1"></a>urbanization2<span class="ot">&lt;-</span><span class="fu">subset</span>(urbanization, <span class="at">select=</span><span class="fu">c</span>(Code, urbanization, Year))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb89"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb89-1"><a href="#cb89-1" aria-hidden="true" tabindex="-1"></a>merged<span class="ot">&lt;-</span><span class="fu">left_join</span>(life_expectancy, urbanization2, <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"Code"</span><span class="ot">=</span><span class="st">"Code"</span>, <span class="st">"Year"</span><span class="ot">=</span><span class="st">"Year"</span>))</span>
<span id="cb89-2"><a href="#cb89-2" aria-hidden="true" tabindex="-1"></a>merged<span class="ot">&lt;-</span><span class="fu">na.omit</span>(merged)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>What is the correlation in life expectancy and urbanization for the entire dataset?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb90"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb90-1"><a href="#cb90-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(merged<span class="sc">$</span>life_expectancy_values, merged<span class="sc">$</span>urbanization)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.4579985</code></pre>
</div>
</div>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



<script src="lab8_questions_files/libs/quarto-html/zenscroll-min.js"></script>
</body></html>